name: GreaterSapien
favicon: null
layout_spectrum: 0.43652861495502293
typography_spectrum: 0.5449128246400505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7863918433431536
  lightness: 0.5263710902072489
  saturation: 0.6167302108369768
  rhythmicContrast: 0.7819638750515878
purpose: []
